services:
  fastapi:
    build: ./fastapi
    container_name: biblioteca_fastapi
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:////fastapi/biblioteca.db
      - LOG_LEVEL=INFO
      - SEED_ON_STARTUP=true
    volumes:
      - mis_datos:/fastapi
    networks:
      - biblioteca_net

  streamlit:
    build: ./streamlit
    container_name: biblioteca_streamlit
    depends_on:
      - fastapi
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://fastapi:8000
    networks:
      - biblioteca_net

networks:
  biblioteca_net:
    driver: bridge

volumes:
  mis_datos:
