"""Interfaces (protocols) de los repositorios.

Aplica:
* DIP: los servicios dependen de estas abstracciones, no de la
  implementación concreta de SQLAlchemy.
* ISP: cada repositorio expone solo los métodos que necesita su consumidor.
* OCP: para cambiar de SQLite a Postgres o a memoria basta con escribir
  otra implementación; los servicios no se tocan.
"""
from __future__ import annotations

from typing import Iterable, List, Optional, Protocol

from ..domain.models import Libro, Prestamo, Usuario


class LibroRepositoryProtocol(Protocol):
    def listar(self) -> List[Libro]: ...
    def obtener(self, libro_id: int) -> Optional[Libro]: ...
    def crear(self, titulo: str, autor: str, genero: str) -> Libro: ...
    def buscar(self, texto: str) -> List[Libro]: ...
    def stream(self) -> Iterable[Libro]: ...


class UsuarioRepositoryProtocol(Protocol):
    def listar(self) -> List[Usuario]: ...
    def obtener(self, usuario_id: int) -> Optional[Usuario]: ...
    def por_email(self, email: str) -> Optional[Usuario]: ...
    def crear(self, nombre: str, email: str) -> Usuario: ...


class PrestamoRepositoryProtocol(Protocol):
    def crear(self, libro_id: int, usuario_id: int) -> Prestamo: ...
    def obtener(self, prestamo_id: int) -> Optional[Prestamo]: ...
    def activos_por_libro(self, libro_id: int) -> List[Prestamo]: ...
    def por_usuario(self, usuario_id: int) -> List[Prestamo]: ...
